name: manual approval

on:  
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  notify-and-approve:
    runs-on: ubuntu-latest
    name: Build Plan
    permissions:
      issues: write  # Grant write permission for issues
      contents: read  # Grant read permission for repository contents
    
    
    steps:
      - name: Notify Admin
        run: echo "Notification sent to admin for approval."        
  
      - name: Await Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          #secret: ${{ secrets.APPTOKEN }}          
          secret: ${{ secrets.GITHUB_TOKEN }}  # Use the GITHUB_TOKEN
          approvers: duykhanh2104 # Replace with GitHub usernames
          minimum-approvals: 1
          issue-title: "Manual Approval Required for Action Apply"
          issue-body: "Please approve or deny the deployment."
          additional-approved-words: ''
          additional-denied-words: ''
          exclude-workflow-initiator-as-approver: false
  run-tests:
    needs: notify-and-approve
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          echo "Running tests...here"          
